---
title: "Now Boarding: Team Code & Software"
date: "`r Sys.Date()`"
author: "Neha Moopen"
github: "nehamoopen/cs-onboarding"
#logo: "logo_gallery.png"
output:
  epuRate::epurate:
    toc: FALSE
    number_sections: FALSE
    code_folding: "hide"
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_file = "docs/index.html"
    )
  })
---

<br>

> Team Code & Software is a 'sub-team' within RDM Support, officially formed in academic year 2022-2023. This document introduces the team and outlines its goals and activities.  

## Introduction 

Team Code & Software focuses on support that equips UU researchers to work in line with open science and the FAIR principles for data and software. 

The team, along with RDM Support, is contributing to the following [strategic goals of the UB](https://www.uu.nl/sites/default/files/UB-Policy-Plan-2022-2025-PDF-4MB.pdf):

- The Utercht University community is information-literate with regards to publications, data, code and software.
- Utrecht University's scholarly output is open or FAIR.
- Utrecht University's educational resources are FAIR.

Our activities largely involve consultancy and training, as well as community building. 

The team can also provide hands-on/structural support depending on team members' expertise and availability. Typically, team members based at the UB would provide support for research data management, while larger scientific computing projects would be taken up by the Research Engineering team based at ITS.   

We don’t (necessarily) provide support on statistics and analyses that would typically be covered in faculties and study programs. 

The contactpersons for the team are:

- [Neha Moopen](n.moopen@uu.nl) @UB. 
- [Jelle Treep](https://www.uu.nl/medewerkers/HJTreep) @ResearchEngineering

## Workshops & Lectures

We currently provide the following workshops & lectures:

1. Introduction to R & Data: [course website](https://utrechtuniversity.github.io/workshop-introduction-to-R-and-data/) / [GitHub repository](https://github.com/UtrechtUniversity/workshop-introduction-to-r-and-data)
2. Best Practices in writing Reproducible Code: [course website](https://utrechtuniversity.github.io/workshop-computational-reproducibility/docs/index.html) / [GitHub repository](https://github.com/UtrechtUniversity/workshop-computational-reproducibility)
3. Writing a Reproducible Manuscript in R with WORCS: [course website](https://nehamoopen.github.io/worcshop-book/) / [GitHub repository](https://github.com/nehamoopen/worcshop-book)
4. Getting Started With Computational Reproducibility: [slides](https://github.com/UtrechtUniversity/computational-reproducibility) / [GitHub repository](https://github.com/UtrechtUniversity/computational-reproducibility)

The following workshops are under development or just ideas:

- REBO Skills Academy: Text-Mining in R (in development): [GitHub repository](https://github.com/UtrechtUniversity/workshop-rebo-skills-academy-2023)
- Introduction to Python & Data (in development)
- Git & GitHub
- Literaure Searches & Systematic Reviews in R: [GitHub issue](https://github.com/nehamoopen/digital-garden/issues/42)
- Data Visualization
- Linked Open Data: [GitHub repository](https://github.com/nehamoopen/lessons-in-lod)
- Shell Commands/Scripting

<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">

TO-DOs:

- Develop course materials for REBO Text-Mining workshop.
- Review content of ongoing workshops.
- Convert Introduction to R & Data website to [bookdown](https://pkgs.rstudio.com/bookdown/).
- Update bookdown theme for all workshops to match UU style.
- Create reproducible presentation for the reproducibility lecture.
- Review workshop webpages.
- Review FormDesk registration forms.
- Pre-workshop email templates.
- Post-workshop email templates.
- Automate workshop certificates.
- Archive workshop materials on Zenodo and obtain a DOI.

</div>

## Programming Cafe

The [Programming Cafe](https://www.uu.nl/en/research/research-data-management/walk-in-hours-workshops/programming-cafe) is an informal community event that takes place on a monthly basis. During this event, we knowledge about programming through short presentations and also help each other with challenges in working with code and data. 
It is a ‘relaunch’ of the popular [R Café](https://github.com/UtrechtUniversity/R-data-cafe) that used to take place before the coronavirus outbreak. We broadened the event to include programming languages other than R.

Link to GitHub repository: https://github.com/UtrechtUniversity/programming-cafe

<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">

TO-DOs:

- Update Programming Cafe GitHub repository
- Attend and/or co-organize the Programming Cafe.

</div>

## Consultancy

During the [Walk-In Hours for Research Data & Software](https://www.uu.nl/en/research/research-data-management/walk-in-hours-workshops/walk-in-hours-research-data-software) which take plce on a weekly basis, we provide consultancy such as advice and one-on-one support. 

We also provide consultancy via email/TopDesk. Questions may be resolved via email/TopDesk or they could lead to follow-up appointments.

<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">

TO-DOs:

- Attend the Walk-In Hours & keep an eye on TopDesk.

</div>

## Website & Communications

The RDM Support website only recently got a tab for guides related to [Software & Computing](https://www.uu.nl/en/research/research-data-management/tools-services/software-and-computing). The team can create more guides for coding and software to accompany those already available for research data.

<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">

TO-DOs:

- Decide (as a team) what guides are relevant for researchers.
- Prioritize and develop the guides.

</div>

## RDM Utilities

Neha recently created a GitHub repository for [RDM Utilities](https://github.com/UtrechtUniversity/rdm-utilities). The idea is to create code snippets/tutorials/cheatsheets that facilitate research data management, including FAIRification. It is aimed at colleagues in data and software support, but it can be used by tech-savvy researchers as well.

This repository can also be linked to the guides we want to put on the RDM Support website.

<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">

TO-DOs:

- Work through and update the proposed utilities in the repository.
- Write up on new utilities if they're relvant.

</div>

## Course Catalog

The trainings provided by Team Code & Software emphasize basic and foundational skills, but it would be useful to have a catalog of trainings on code & software provided across the UU. This would give us an overview of what is and isn't taught at the UU currently and help us point researchers to courses and workshops relevant for them or consider developing a training ourselves.

<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">

TO-DOs:

- Coordinate with faculty liaisons and information specialists to find out what courses are being delivered at the faculties.
- Discuss with Team Learning on the best way to catalog the workshop information.

</div>

## Community Building

In order to better situate the team within the UU, we need to meet with and develop our relationship with others who are working with or promoting coding & software skills. These parties include, but are not limited to:

- Center for Digital Humanities
- The various Graduate Schools
- ITS
- FAIR Data & Software Fellows
- OSCU Ambassadors

<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">

TO-DOs:

kinda self-explanatory, we need to plan meetings...

</div>

## Prequisites (sort of) to Getting Started

It would be to have working knowledge of:

- R and/or Python.
- Git & GitHub for collaboration.
- [bookdown](https://pkgs.rstudio.com/bookdown/) and/or [JupyterBook](https://jupyterbook.org/en/stable/intro.html) to build course websites.

